name: 5400-final-project
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - requests
  - beautifulsoup4
  - nltk
  - spacy
  - gensim
  - pytest
  - pip
  - transformers
  - scikit-learn
  - matplotlib
